tables:
  - tourism_info
db:
  url: jdbc:mysql://127.0.0.1:3306/hotel-v3?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: Root@123
author: Enigma
#输出路径
output: /Users/Enigma/WorkSpace/IdeaProjects/eg-service/code-generate
pkg:
  parent: com.fnk.app
  module: hotel
swagger: true