<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fnk</groupId>
        <artifactId>service-common</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>service-common-db</artifactId>

  <dependencies>
      <dependency>
          <groupId>com.baomidou</groupId>
          <artifactId>mybatis-plus-boot-starter</artifactId>
          <exclusions>
              <exclusion>
                  <groupId>org.mybatis</groupId>
                  <artifactId>mybatis-spring</artifactId>
              </exclusion>
          </exclusions>
      </dependency>
      <dependency>
          <groupId>org.mybatis</groupId>
          <artifactId>mybatis-spring</artifactId>
      </dependency>
      <dependency>
          <groupId>com.mysql</groupId>
          <artifactId>mysql-connector-j</artifactId>
      </dependency>
      <dependency>
          <groupId>com.fnk</groupId>
          <artifactId>service-common-bean</artifactId>
      </dependency>
      <dependency>
          <groupId>com.fnk</groupId>
          <artifactId>service-common-tools</artifactId>
      </dependency>
      <dependency>
          <groupId>org.springdoc</groupId>
          <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      </dependency>
  </dependencies>

</project>
